name: test.yml

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Set up Maven
        run: mvn clean install -f ./pom.xml

      - name: Run Unit Tests
        run: mvn test --file pom.xml
